TFDS-1530: Block github direct file

diff --git a/.github/workflows/github-md-validator.yaml b/.github/workflows/github-md-validator.yaml
--- a/.github/workflows/github-md-validator.yaml
+++ b/.github/workflows/github-md-validator.yaml
@@ -1,53 +1,75 @@
 name: Markdown Validator
 on:
+  workflow_dispatch:
   workflow_call:
-  # Triggers the workflow on push or pull request events but only for the dev , stage and main branch
-  push:
-    branches: [ develop,stage,preview,main ]
-  pull_request:
-    branches: [ develop,stage,preview,main ]
-    paths:
-      - 'docs/**' 
+    outputs:
+      statuscheck:
+        description: "Output of markdown validation job"
+        value: ${{ jobs.markdown_validator_actions.outputs.output1 }}
 
 jobs:
-  MD-Validator-Action:
+  MD_Validator_Action:
     runs-on: ubuntu-latest
+    timeout-minutes: 15
+    outputs:
+      output1: ${{ steps.markdown_validate.outputs.JobStatus }}
     steps:
       - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
       - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
-      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}." 
+      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
       - name: Creating new temp sub dir called `tools`
         run: |
-         mkdir -m 777 tools
-         cd tools
-         pwd
-         ls -la
+          mkdir -m 777 tools
+          cd tools
+          pwd
+          ls -la
       - name: Check out ${{ github.repository }} Repo code at ${{ github.workspace }}
         uses: actions/checkout@main
         with:
-         repository: ${{ github.repository }}
-         path: ${{ github.workspace }}
+          repository: ${{ github.repository }}
+          path: ${{ github.workspace }}
       - name: Check out Fiserv/remote-actions Repo code at ${{ github.workspace }}/tools
         uses: actions/checkout@main
         with:
-         repository: Fiserv/remote-actions
-         ref: develop
-         path: ${{ github.workspace }}/tools
+          repository: Fiserv/remote-actions
+          ref: main
+          path: ${{ github.workspace }}/tools
       - name: List files in the repository
         run: |
-         cd ${{ github.workspace }}
-         pwd
-         ls -la
-         cd ${{ github.workspace }}/tools
-         pwd
-         ls -la
+          cd ${{ github.workspace }}
+          pwd
+          ls -la
+          cd ${{ github.workspace }}/tools
+          pwd
+          ls -la
       - run: echo "💡 The ${{ github.repository }} repository has been cloned on root"
       - run: echo "🖥️ The workflow is now ready to test your code on the runner."
       - name: List files in the repository
         run: |
-         pwd
-         ls -la
-      - name: Running MarkDown Validator.....
+          pwd
+          ls -la
+
+      - name: Cache node modules
+        id: cache-npm
+        uses: actions/cache@main
+        env:
+          cache-name: cache-node-modules
+        with:
+          # npm cache files are stored in `~/.npm` on Linux/macOS
+          path: ~/.npm
+          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
+          restore-keys: |
+            ${{ runner.os }}-build-${{ env.cache-name }}-
+            ${{ runner.os }}-build-
+            ${{ runner.os }}-
+
+      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
+        name: List the state of node modules
+        continue-on-error: true
+        run: npm list
+
+      - name: Running Markdown Validator.....
+        id: markdown_validate
         run: |
           pwd
           cd ${{ github.workspace }}/tools/scripts
@@ -67,15 +89,8 @@ jobs:
           rm -rf ${{github.workspace }}/tools
           echo "Temp tools directory deleted ......"
           if [[ $result == *'VALIDATOR FAILED'* ]] ;then
-          echo "Validator failed and exiting the Job..."
-          exit 1
+            echo "Validator failed and exiting the Job..."
+            exit 1 
           elif [[ $result == *'PASSED'* ]] ;then
-          echo "Validator Ran Successfully....🍏"
-          fi
-      - run: echo "🍏 This job's status is ${{ job.status }}."
-      - name: Show file content
-        run: |
-          pwd
-          ls -la
-      # - name: Commited changes from action runner to remote branch
-      #   uses: stefanzweifel/git-auto-commit-action@v4
+            echo "Validator Ran Successfully....🍏"
+      - run: echo "🍏 This job's status is ${{ job.status }} and output - ${{ steps.apivalidate.outputs.JobStatus }}"
